config/routes.rb
Jhad::Application.routes.draw do

  

  root 'dreams#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations' }

  devise_scope :user do
    match '/sso',    to: 'discourse_sso#sso',    via: 'get'
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dreams do
    resources :comments
    member do
      put 'like', to: "dreams#upvote"
      put "dislike", to: "dreams#downvote"
    end
  end

  resources :articles do
    resources :comments
  end
  
  resources :conversations, only: [:index, :show, :destroy, :new] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]
  resources :notifications
  resources :hashtags
  resources :screennames
  resources :relationships, only: [:create, :destroy]
  

  match '/feed',    to: 'static_pages#home',    via: 'get'
  match '/blog',    to: 'articles#index',    via: 'get'
  match '/faq',    to: 'static_pages#faq',    via: 'get'
  match '/resources',    to: 'static_pages#resources',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/about2',   to: 'static_pages#about2',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/graph', to: 'static_pages#graph', via: 'get'
  match '/test', to: 'static_pages#test', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/sitemap.xml', to: 'static_pages#sitemap', format: 'xml', as: :sitemap, via: 'get'

  

  

  get 'dreams/new' => 'dreams#new', :as => :new     # For new dream modal

  get ':controller(/:action(/:id))'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

    if user_signed_in?
      @user = current_user
      @dreams = @user.feed.where(private: false)
    else
      @dreams = Dream.all.where(private: false)
    end

    @filterrific = initialize_filterrific(
      @dreams,
      params[:filterrific],
      select_options: {
        with_emotion_id: Emotion.options_for_select
      },
      default_filter_params: { search: params[:search] },
    ) or return 

    @dreams = @filterrific.find

    if params[:sort] == 'trending'
      @dreams = @dreams.hot
    elsif params[:sort] == 'submitted'
      @dreams = @dreams.regular
    elsif params[:sort] == 'dreamed'
      @dreams = @dreams.chronological
    else
      @dreams = @dreams.hot
    end  



    @dreams2 = @dreams.paginate(page: params[:page],per_page: 15)
    @page_number = params[:page].to_i
    if params[:page].nil?
      @dreams = @dreams.paginate(page: params[:page],per_page: 15)
    elsif params[:page] == 1
      @dreams = @dreams.paginate(page: params[:page],per_page: 15)
    else
      @cumul = @dreams.paginate(page: 1,per_page: 15)
      (@page_number - 1).times do |i|
        @dreams.paginate(page: i + 2,per_page: 15).each do |dream|
          @cumul = @cumul << dream
        end
      end
      @dreams = @cumul
    end



    @hashes = Hash.new
    @emotions = Hash.new

    @dreams.each do |dream|
      dream.emotions.each do |emotion|
        if @emotions[emotion.id].nil?
          @emotions[emotion.id] = 1
        else
          @emotions[emotion.id] += 1
        end
      end   

      dream.hashtags.each do |hashtag|
        if @hashes[hashtag.id].nil?
          @hashes[hashtag.id] = 1
        else
          @hashes[hashtag.id] += 1
        end
      end
    end

    @emotions = @emotions.sort_by { |k, v| v }
    @emotions.reverse!  

    @hashes = @hashes.sort_by { |k, v| v }
    @hashes.reverse!

  # Graph logic

    @word_count = Hash.new
    # Create hash of word frequencies in all relevant dreams
    @dreams.each do |dream|
      dream.word_freq.each do |stem, info_array|
        if @word_count[info_array[0]] == nil
          @word_count[info_array[0]] = { freq: info_array[1], dream_ids: [dream.id] }
        else
          @word_count[info_array[0]][:freq] += info_array[1]
          @word_count[info_array[0]][:dream_ids].push(dream.id)
        end
      end
    end
    # Create hash with key = word_id, and v = freq, to be sortable
    @word_count_sort = Hash.new(0)
    @word_count.each do |k, v|
      @word_count_sort[k] = v[:freq]
    end
    
    @word_count_sort = @word_count_sort.sort_by { |k, v| v }
    @word_count_sort.reverse!

    if params[:graph]
      @min_words_constant = 15
      @min_assocs_constant = 2
    else
      @min_words_constant = 5
      @min_assocs_constant = 2
    end

    @nodes = Array.new

    @min_words = [@word_count.length, @min_words_constant].min
    @min_words.times do |n|
      @nodes.push(@word_count_sort[n][0])     #@word_count_sort has become an array.
    end

    @links = Array.new

    @min_words.times do |n|
      @word_object_id = @nodes[n]
      @word_object_assocs = Hash.new(0)
      @word_object_dreams = @word_count[@word_object_id][:dream_ids]

      @word_object_dreams.each do |dream_id|
        Dream.find(dream_id).word_freq.each do |stem, info_array|
          if info_array[0] != @word_object_id
            @word_object_assocs[info_array[0]] += info_array[1]
          end
        end
      end

      @word_object_assocs = Hash[@word_object_assocs.sort_by{|k, v| v}.reverse]
      @min_assocs = [@word_object_assocs.length, @min_assocs_constant].min
      @min_assocs.times do |i|
        if @nodes.include? @word_object_assocs.keys[i]    # if the association is already a node
          @links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])]) # write the link
        else @nodes.include? @word_object_assocs.keys[i]    
          @nodes.push(@word_object_assocs.keys[i])
          @links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])])
        end
      end
    end


    @node_text = "["
    @nodes.each do |word_id|

      @node_text += "{\"name\":\"#{word_id}\",\"value\":#{@word_count[word_id][:freq]}},"
    end
    @node_text = @node_text[0..-2] unless @nodes.empty?       # remove extra comma

    @node_text += "]"

    @link_text = "["
    @links.each do |link|
      @link_text += "{\"source\":#{link[0]},\"target\":#{link[1]}},"
    end

    @link_text = @link_text[0..-2] unless @links.empty?   # remove extra comma

    @link_text += "]"

    @graph_text = "{\"nodes\":#{@node_text},\"links\":#{@link_text}}" 

  # end    # What does this end?  

    respond_to do |format|
      format.html
      format.js
    end

  end

  def help
  end

  def about
  end

  def about2
  end

  def contact
  end

  def blog
  end

  def resources
  end

  def faq
  end

  def graph
  end

  def tos
  end

  def search
    @searchitems = PgSearch.multisearch(params[:query])
    @dreams = []
    @dream_items = @searchitems.where(searchable_type: "Dream")

    if params[:impression].present?   
      @dream_items.each do |dream_item|
        if Dream.find(dream_item.searchable_id).private == false    # If dream is public, include it in search
          if Dream.find(dream_item.searchable_id).impression >= params[:impression].to_f
            @dreams.push(Dream.find(dream_item.searchable_id))
          end
        end
      end
    else
      @dream_items.each do |dream_item|
        if Dream.find(dream_item.searchable_id).private == false    # If dream is public, include it in search
          @dreams.push(Dream.find(dream_item.searchable_id))
        end
      end
    end

    @dreams_raw = @dreams

    @users = []
    @user_items = @searchitems.where(searchable_type: "User")
    @user_items.each do |user_item|
      @users.push(User.find(user_item.searchable_id))
    end

  # Graph logic

    @word_count = Hash.new
    # Create hash of word frequencies in all relevant dreams
    @dreams_raw.each do |dream|
      dream.word_freq.each do |stem, info_array|
        if @word_count[info_array[0]] == nil
          @word_count[info_array[0]] = { freq: info_array[1], dream_ids: [dream.id] }
        else
          @word_count[info_array[0]][:freq] += info_array[1]
          @word_count[info_array[0]][:dream_ids].push(dream.id)
        end
      end
    end
    # Create hash with key = word_id, and v = freq, to be sortable
    @word_count_sort = Hash.new(0)
    @word_count.each do |k, v|
      @word_count_sort[k] = v[:freq]
    end
    
    @word_count_sort = @word_count_sort.sort_by { |k, v| v }
    @word_count_sort.reverse!

    if params[:graph]
      @min_words_constant = 15
      @min_assocs_constant = 2
    else
      @min_words_constant = 5
      @min_assocs_constant = 2
    end  

    @nodes = Array.new
    @min_words = [@word_count.length, @min_words_constant].min
    @min_words.times do |n|
      @nodes.push(@word_count_sort[n][0])     #@word_count_sort has become an array.
    end

    @links = Array.new

    @min_words.times do |n|
      @word_object_id = @nodes[n]
      @word_object_assocs = Hash.new(0)
      @word_object_dreams = @word_count[@word_object_id][:dream_ids]

      @word_object_dreams.each do |dream_id|
        Dream.find(dream_id).word_freq.each do |stem, info_array|
          if info_array[0] != @word_object_id
            @word_object_assocs[info_array[0]] += info_array[1]
          end
        end
      end

      @word_object_assocs = Hash[@word_object_assocs.sort_by{|k, v| v}.reverse]
      @min_assocs = [@word_object_assocs.length, @min_assocs_constant].min
      @min_assocs.times do |i|
        if @nodes.include? @word_object_assocs.keys[i]    # if the association is already a node
          @links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])]) # write the link
        else @nodes.include? @word_object_assocs.keys[i]    
          @nodes.push(@word_object_assocs.keys[i])
          @links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])])
        end
      end
    end


    @node_text = "["
    @nodes.each do |word_id|

      @node_text += "{\"name\":\"#{word_id}\",\"value\":#{@word_count[word_id][:freq]}},"
    end
    @node_text = @node_text[0..-2] unless @nodes.empty?       # remove extra comma

    @node_text += "]"

    @link_text = "["
    @links.each do |link|
      @link_text += "{\"source\":#{link[0]},\"target\":#{link[1]}},"
    end

    @link_text = @link_text[0..-2] unless @links.empty?   # remove extra comma

    @link_text += "]"

    @graph_text = "{\"nodes\":#{@node_text},\"links\":#{@link_text}}"    

  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_old.html.erb
<% provide(:title, 'About' ) %>
<div id="home-top-panel" class="text-center">
	<div id="home-header">dreamly</div>	
	<div id="home-byline">the social dream journal app</div>
	<div id="home-byline2">
		free | private | social
	</div>
	<%= link_to(new_user_session_path, { :remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window-login'}) do %>
		<button type="button" id="signup-button" class="btn btn-primary btn-lg">
			<span>Sign up!</span>
		</button>
	<% end %>
</div>

<div class="home-panel1">
	Dreamly is a free social dream journal that allows you to keep track of your dreams and map your unconscious thoughts.
</div>

<div id="home-panel2">
	<div id="home-panel2-inner">
		<div id="panel2-1" class="col-md-3 col-md-offset-2 white-panel">
			<h3>Automatic word association</h3>
			<p>Discover hidden trends, patterns and associations in your unconscious mind.</p>
		</div>	
		<div id="panel2-2" class="col-md-3 col-md-offset-2 white-panel">
			<h3>Smartphone friendly</h3>
			<p>Journal your dreams without getting up from your bed! Dreamly was designed to be used with your smartphone - no need to download an app.</p>
			<%= image_tag("iphone.png", alt: "Mobile friendly") %>
		</div>
		<%= render 'shared/graph' %>
	</div>

</div>

<div class="home-panel3">
	<div class="home-panel3-inner">
		<div id="panel3-1" class="col-md-3 col-md-offset-2 white-panel">
			<h3><span class="glyphicon glyphicon-user"></span> Social</h3>
			<p>Follow the dreams of your friends and favorite celebrities. Share comments and interpretations.</p>
		</div>	
		<div id="panel3-2" class="col-md-3 col-md-offset-2 white-panel">
			<h3><span class="glyphicon glyphicon-eye-open"></span> Private</h3>
			<p>Dreams can reveal your deepest secrets, so we take privacy very seriously at Dreamly. You can choose to make a dream public or private at any time. Information from private dreams will never be shown to anyone except you. You can also use the @ character to censor any word within a public dream.</p>
		</div>
	</div>	
</div>

<div class="home-panel1">
	<p>Merrily, merrily, merrily, merrily;</p>
	<p>life is but a dream.</p>
</div>

<div class="home-panel3">
	<div class="home-panel3-inner">
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('smile-o') %></span> Emoticons</h3>
			<p>Dreamly uses a library of keywords to automatically tag dreams according to seven fundamental emotions (Happy, Sad, Afraid, Desiring, Angry, and Guilty).</p>
		</div>	
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('slack') %></span> Hashtags</h3>
			<p>Just like twitter, you can put a #hashtag before any word in a dream to categorize it. </p>
		</div>
	</div>	
</div>

<div class="home-panel3">
	<div class="home-panel3-inner">
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('ra') %></span> @Names</h3>
			<p>You can put the @ character before any word in your dream to 1) blur the word from public view and 2) track the word across multiple dreams. This is intended mainly to use to anonymyze and track the names of people, places, and things in your dreams.</p>
		</div>	
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('warning') %></span> Impact</h3>
			<p>Some dreams are trivial, but others are epic sagas revealing the depth and breadth of your soul with a cinematic storyline and vivid visuals. Dreamly lets you differentiate between the two by choosing an Impact level setting of Normal, Substantial, or Epic.</p>
		</div>
	</div>	
</div>

<div class="home-panel1">
	<p>Deep into that darkness peering, long I stood there, wondering, fearing, doubting, dreaming dreams no mortal ever dared to dream before.<p>
	<p>- Edgar Allan Poe</p>
</div>

<div class="home-panel3">
	<div class="home-panel3-inner">
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('ra') %></span> Voting</h3>
			<p>Users can upvote or downvote any public dream. The highest voted dreams will display at the top of the page. </p>
		</div>	
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('warning') %></span> Comments</h3>
			<p>Users can comment on any public dream. The most valuable and comments will be useful dream interpretations. </p>
		</div>
	</div>	
</div>

<div class="home-panel3">
	<div class="home-panel3-inner">
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('ra') %></span> Filter and Sort</h3>
			<p>You can sort dreams by “Trending”, “New”, or “Dreamed”. “Trending” uses an algorithm based on the dream’s voting score and time of submission, so that newer, top-voted dreams are displayed first.</p>
			<p>You can filter dreams by search term, emotion, and impact level.<p>
		</div>	
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('warning') %></span> Following</h3>
			<p>Just like twitter, you can follow other users and they can follow you.</p>
		</div>
	</div>	
</div>

<div class="home-panel1">
	<p>The future belongs to those who believe in the beauty of their dreams.<p>
	<p>- Eleanor Roosevelt</p>
</div>

<div class="home-panel3">
	<div class="home-panel3-inner">
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('ra') %></span> Notifications</h3>
			<p>You are notified when someone comments on your dream or a dream you have commented on, when someone follows you, or when someone you are following posts a dream. </p>
		</div>	
		<div class="col-md-3 col-md-offset-2 white-panel">
			<h3><%= icon('warning') %></span> Private messages</h3>
			<p>You can send a private message to any user by clicking the envelope button beneath their name. All of your conversations are shown in your <a href='http://dreamly.io/conversations'>inbox</a>. We encourage users to engage in social therapy via this messaging system. Dreams can act simultaneously as both therapist and patient, sharing their emotions and feelings, and drawing upon each others dreams for analysis.</p>
		</div>
	</div>	
</div>



<%= render 'layouts/footer' %>

app/views/static_pages/graph.html.erb
<canvas id="viewport" width="800" height="600"></canvas>

app/views/static_pages/home.html.erb
<% if params[:graph] %>
	<div id="graph-full" class="white-panel">
		<h3 class="graph-title"><%= impression_status().titleize %>
			<% unless params[:impression] %>
				All
			<% end %>
			dreams
			<% if params[:query] %>
			about <strong><%= params[:query] %></strong>
			<% end %>
		</h3>
		<%= link_to dreams_path(query: params[:query], impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Minimize"} do %>
			<%= icon('compress') %>
		<% end %>	
	</div>
	<%= render 'dreams/graph_full' %>
<% else %>

<% provide(:title, 'All dreams') %>

<div class="row">
	<div class ="col-md-3">
		<div id="profile-left-sidebar">
			<div>
				<% unless user_signed_in? %>

				<div class="login-box">
				<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), wrapper: :inline_form) do |f|%>
				
						<%= f.input :login, placeholder: 'username', input_html: { :class => "login-form username-login-form" } %>
						<%= f.input :password, placeholder: 'password', input_html: { :class => "login-form" } %>
			
	
					<div class="login-box-lower">
				    <%= f.check_box :remember_me %>
				    <span class ="login-small-words">
				    	<span style="padding-right: 5px;">remember me</span>
				    	<%= link_to "reset password", new_password_path(resource_name) %>
						</span>
				    <button type="submit" class="btn btn-primary submit-btn-2">
				      sign in
				    </button>
				  </div>

				<% end %>
	

    <div id="login_error_explanation_wrapper" class="alert alert-danger" style="display:none;">
      <button type="button" class="close" data-hide="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <div id="login_error_explanation"></div>
    </div>		



    <span class="login-small-words" style="position: relative; top: 3px; color: #555555">sign in with</span>
   	<div id="oauth-links">
      <%= link_to(omniauth_authorize_path(resource_name, :google_oauth2), :class => "btn btn-login-2", :id => "google-login") do %>
        <%= icon('google') %>
      <% end %>
      <%= link_to(user_omniauth_authorize_path(:facebook), :class => "btn btn-login-2", :id => "facebook-login") do %>
        <%= icon('facebook') %>
      <% end %>         
      <%= link_to(omniauth_authorize_path(resource_name, :twitter), :class => "btn btn-login-2", :id => "twitter-login") do %>
        <%= icon('twitter') %>
      <% end %>
      <%= link_to(omniauth_authorize_path(resource_name, :yahoo), :class => "btn btn-login-2", :id => "yahoo-login") do %>
        <%= icon('yahoo') %>
      <% end %>
    </div>

    <%= link_to(new_registration_path(resource_name), { id: "signup_words" }) do %>
        register
    <% end %>    

   
</div>

				<% end %>


				<div class="feed-following">
					<%= link_to following_user_path(@user) do %>
						<span class="stat-header">FOLLOWING: <%= @user.following.count %></span> <br />
					<% end %>
				</div>
				<div>
					<% @user.following.each do |user| %>
						<%= link_to user do %>
							<% if user.avatar_file_name.nil? %>
								<div class="dashboard-avatar-default-thumb">
									<p><%= user.username.first.upcase %></p>
								</div>
							<% else %>
								<div class="dashboard-avatar-thumb">
									<%= image_tag user.avatar.url(:thumb), class: "img-center" %>
								</div>
							<% end %>
						<% end %>
					<% end %>	
				</div>			



				<% if @dreams.any? %>
					<div id="profile-graph" class="white-panel">
						<%= link_to dreams_path(graph: true, query: params[:query], impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Fullscreen"} do %>
							<%= icon('arrows-alt') %>
						<% end %>
					</div>
					<div id="profile-graph2">
						<%= render(
							partial: 'dreams/graph',
							locals: { graph_text: @graph_text }
						) %>
					</div>
				<% end %>

				<div id="emotion-listing">
					<%= render(
						partial: 'dreams/emotions',
						locals: { emotions: @emotions }
					) %>
				</div>	

				<div id="hash-listing">
					<%= render(
						partial: 'dreams/tags',
						locals: { hashes: @hashes }
					) %>
				</div>


				<div id="links-panel" class="white-panel">
					<%= link_to "Home", root_path %>
					<%= link_to "About", about_path %>
					<%= link_to "Contact", contact_path %>
					<%= image_tag("footer_stripe.jpg", width: '243', height: '10', class: 'rainbow-bar') %>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-9">
		<div>

			<div class="dream-tabs">
				<% if params[:sort] == "trending" %>
					<ul class="nav nav-tabs">
				    <li role="presentation" class="active"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>
				<% elsif params[:sort] == "submitted" %>	
					<ul class="nav nav-tabs">
				    <li role="presentation"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation" class="active"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>
				<% elsif params[:sort] == "dreamed" %>	
					<ul class="nav nav-tabs">
				    <li role="presentation"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation" class="active"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>		
				<% else %>	
					<ul class="nav nav-tabs">
				    <li role="presentation" class="active"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>										
				<% end %>
			</div>

			<div id ="filter-block">
				<%= form_for_filterrific @filterrific do |f| %>
								
						<%= f.text_field(
							:search,
							placeholder: 'Search...',
							class: 'filterrific-periodically-observed'
						) %>				

					
						<%= f.select(
							:with_emotion_id,
							@filterrific.select_options[:with_emotion_id],
							{ include_blank: 'Emotion' },
							class: "select-js"
						) %>
		

						<%= f.select(
							:impression,
							[['Normal', 1], ['Substantial', 2], ['Epic', 3]],
							{ include_blank: 'Impact' },
							class: "select-js"
						) %>
		
					<%= link_to(reset_filterrific_url) do %>
						<%= icon('times') %>
					<% end %>	

					<%= render(
						partial: 'dreams/list_count',
						locals: { dreams: @dreams }
					) %>		
				
					<div>
						<%= render_filterrific_spinner %>
					</div>
			
				<% end %>
			</div>

			<%= render(
				partial: 'dreams/list',
				locals: { dreams: @dreams, dreams2: @dreams2, page_number: @page_number }
			) %>

			<%= button_tag(:id => "load-more2", :class => "btn btn-primary") do %>
				<%= icon('plus') %>
				<span id="load-more-text">load more</span>
			<% end %>					
				

	</div>
</div>

<% end %>

app/views/static_pages/search.html.erb
<% if params[:graph] %>
	<div id="graph-full" class="white-panel">
		<h3 class="graph-title"><%= impression_status().titleize %>
			<% unless params[:impression] %>
				All
			<% end %>
			dreams
			<% if params[:query] %>
			about <strong><%= params[:query] %></strong>
			<% end %>
		</h3>
		<%= link_to search_path(query: params[:query], impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Minimize"} do %>
			<%= icon('compress') %>
		<% end %>	
	</div>
	<%= render 'dreams/graph_full' %>
<% else %>

<% provide(:title, "Search - #{params[:query]}") %>

<div class="row">
	<div class ="col-md-3">
		<div id="profile-left-sidebar">
			<div data-spy="affix" data-offset-top="23">
				<% if @dreams.any? %>
					<div id="profile-graph" class="white-panel">
						<%= link_to search_path(graph: true, query: params[:query], impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Fullscreen"} do %>
							<%= icon('arrows-alt') %>
						<% end %>						
					</div>
					<%= render 'dreams/graph' %>
				<% end %>
				<div id="links-panel" class="white-panel">
					<%= link_to "Home", root_path %>
					<%= link_to "About", about_path %>
					<%= link_to "Contact", contact_path %>
					<%= image_tag("footer_stripe.jpg", width: '243', height: '10', class: 'rainbow-bar') %>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-9">
		<h3 class="content-title">Results for <strong><%= params[:query] %></strong></h3>

		<ul class="nav nav-pills nav-pills-inline" role="tablist">
			<% if params[:impression] == '2' %>
				<li><%= link_to "All", search_path(query: params[:query]) %></li>
				<li class="active"><%= link_to "Big", search_path(query: params[:query], impression: 2) %></li>
				<li><%= link_to "Huge", search_path(query: params[:query], impression: 3) %></li>
			<% elsif params[:impression] == '3' %>
				<li><%= link_to "All", search_path(query: params[:query]) %></li>
				<li><%= link_to "Big", search_path(query: params[:query], impression: 2) %></li>
				<li class="active"><%= link_to "Huge", search_path(query: params[:query], impression: 3) %></li>
			<% else %>
				<li class="active"><%= link_to "All", search_path(query: params[:query]) %></li>
				<li><%= link_to "Big", search_path(query: params[:query], impression: 2) %></li>
				<li><%= link_to "Huge", search_path(query: params[:query], impression: 3) %></li>
			<% end %>
		</ul>

		<% if current_user %>
			<%= link_to "Only my dreams", user_path(current_user.id, query: params[:query]), class: "btn btn-danger btn-square", id: "only-my-dreams-button" %>
		<% end %>

		<ol class="list-unstyled dreams" id ="user-dreams">
			<%= render partial: "dreams/dream", collection: @dreams %>
		</ol>
		<div class="users" id="user-list">
			<%= render partial: "users/user", collection: @users %>
		</div>
	</div>
</div>

<% end %>