config/routes.rb
Jhad::Application.routes.draw do

  

  root 'dreams#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations' }

  devise_scope :user do
    match '/sso',    to: 'discourse_sso#sso',    via: 'get'
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dreams do
    resources :comments
    member do
      put 'like', to: "dreams#upvote"
      put "dislike", to: "dreams#downvote"
    end
  end

  resources :articles do
    resources :comments
  end
  
  resources :conversations, only: [:index, :show, :destroy, :new] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]
  resources :notifications
  resources :hashtags
  resources :screennames
  resources :relationships, only: [:create, :destroy]
  

  match '/feed',    to: 'static_pages#home',    via: 'get'
  match '/blog',    to: 'articles#index',    via: 'get'
  match '/faq',    to: 'static_pages#faq',    via: 'get'
  match '/resources',    to: 'static_pages#resources',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/about2',   to: 'static_pages#about2',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/graph', to: 'static_pages#graph', via: 'get'
  match '/test', to: 'static_pages#test', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/sitemap.xml', to: 'static_pages#sitemap', format: 'xml', as: :sitemap, via: 'get'

  

  

  get 'dreams/new' => 'dreams#new', :as => :new     # For new dream modal

  get ':controller(/:action(/:id))'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	before_action :get_mailbox
	before_action :get_conversation, except: [:index, :empty_trash, :new]
	before_action :get_box, only: [:index]


	def index
		if @box.eql? "inbox"
			@conversations = @mailbox.conversations
#		elsif @box.eql? "sent"
#			@conversations = @mailbox.sentbox
		else
			@conversations = @mailbox.trash
		end

		@conversation = Mailboxer::Conversation.participant(current_user).order('updated_at DESC').first

		@conversations = @conversations.paginate(page: params[:page], per_page: 10)

		current_user.mailbox.notifications.each do |notif|
			notif.mark_as_read(current_user)
		end

	end

	def show
		@conversation = @mailbox.conversations.find(params[:id])

		@conversations = @mailbox.conversations
		@conversations = @conversations.paginate(page: params[:page], per_page: 10)
	end

	def reply
		current_user.reply_to_conversation(@conversation, params[:body])
		user2 = @conversation.recipients[0]
		if user2 == current_user
			user2 = @conversation.recipients[1]
		end
		user2.notify('Message', 'You received a message')
		flash[:success] = 'Reply sent'
		redirect_to conversation_path(@conversation)
	end

	def destroy
		@conversation.move_to_trash(current_user)
		flash[:success] = 'The conversation was moved to trash.'
		redirect_to conversations_path
	end

	def restore
		@conversation.untrash(current_user)
		flash[:success] = 'The conversation was restored.'
		redirect_to conversations_path
	end

	def empty_trash
		@mailbox.trash.each do |conversation|
			conversation.receipts_for(current_user).update_all(deleted: true)
		end
		flash[:success] = "Your trash was cleaned!"
		redirect_to conversations_path
	end

	private

	def get_box
		if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
			params[:box] = "inbox"
		end
		@box = params[:box]
	end

	def get_mailbox
		@mailbox ||= current_user.mailbox
	end

	def get_conversation
		@conversation ||= @mailbox.conversations.find(params[:id])
	end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
	def mailbox_section(title, current_box, opts = {})
		opts[:class] = opts.fetch(:class, '')
		opts[:class] += ' active' if title.downcase == current_box
		content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
	end
end

app/views/conversations/_conversation.html.erb
<%= link_to conversation_path(conversation), class: "message-link" do %>

		<li class="list-group-item clearfix">

			<div class="message-left">
				<% if conversation.participants[0] == current_user %>
					<% participant = conversation.participants[1] %>
				<% else %>
					<% participant = conversation.participants[0] %>
				<% end %>

				<% unless participant == nil %>
					<% if participant.avatar_file_name.nil? %>
						<div class="dream-avatar-default">
							<p><%= participant.username.first.upcase %></p>
						</div>						
					<% else %>
						<%= image_tag participant.avatar.url(:thumb) %>
					<% end %>
				<% end %>
			</div>

			<div class="message-right">
				<% conversation.participants.each do |participant| %>
					<% unless participant == current_user %>
						<span class="message-username"><%= participant.username %></span>
					<% end %>
				<% end %>


				<span class="message-teaser"><%= truncate(conversation.last_message.body) %></span>
					<small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>
			</div>
		</li>

<% end %>

			<div class="btn-group-vertical pull-right trash-button">
				<% if conversation.is_trashed?(current_user) %>
					<%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
				<% else %>
					<%= link_to conversation_path(conversation), class: 'btn btn-xs', method: :delete,
											data: {confirm: 'Are you sure?'} do %>
						<%= icon('times') %>
					<% end %>
				<% end %>
			</div>

app/views/conversations/index.html.erb
<div class="row">


	<div class="col-sm-3">

		<p><%= link_to 'Start conversaton', new_message_path, class: 'btn btn-lg btn-primary' %></p>

		<ul class="nav nav-tabs">
			<%= mailbox_section 'inbox', @box %>
<!--			<%= mailbox_section 'sent', @box %>	-->
			<%= mailbox_section 'trash', @box %>
		</ul>		

		<% if @box == 'trash' %>
			<p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
											data: {confirm: 'Are you sure?'} %></p>
		<% end %>
		<ul class="list-group">
			<%= render partial: 'conversations/conversation', collection: @conversations %>
		</ul>

		<%= will_paginate %>

	</div>

	<div class="col-sm-9">
		<% if @conversation == nil %>
		<% else %>
			<div class="panel panel-default">
				<div class="panel-heading">

					<% @conversation.participants.each do |participant| %>
						<% unless participant == current_user %>
							<span class="message-username"><%= participant.username %></span>
						<% end %>
					<% end %>
				</div>
				<div class="panel-body">
					<div class="messages">
						<% @conversation.receipts_for(current_user).reverse.each do |receipt| %>
							<div class="media">
								<% message = receipt.message %>
								<div class="media-left">
									<div class="dream-left">
										<%= link_to message.sender do %>
											<% if message.sender.avatar_file_name.nil? %>
												<div class="dream-avatar-default">
													<p><%= message.sender.username.first.upcase %></p>
												</div>						
											<% else %>
												<%= image_tag message.sender.avatar.url(:thumb) %>
											<% end %>
										<% end %>
									</div>
								</div>

								<div class="media-body">
									<h6 class="media-heading"><%= message.sender.username %>
										says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
									<%= message.body.html_safe %>
								</div>
							</div>
						<% end %>
					</div>
				</div>
			</div>

			<%= form_tag reply_conversation_path(@conversation), method: :post do %>
				<div class="form-group">
					<%= text_area_tag 'body', nil, cols: 3, class: 'form-control message-reply-box', placeholder: 'Type something...', required: true %>
				</div>
				<%= submit_tag "Send message", class: 'btn btn-primary' %>
			<% end %>
		<% end %>

	</div>
</div>

app/views/conversations/new.html.erb
<h4>Start conversation</h4>

<%= form_tag messages_path, method: :post do %>
<!--
	<div class="form-group">
		<%= label_tag 'message[subject]', 'Subject' %>
		<%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
	</div>
-->

	<%= hidden_field(:message, "subject", value: "New message") %>

	<% if params[:recipient] %>

		<%= hidden_field(:message, "recipients", value: params[:recipient] %>

		<h4>Toshr: <%= User.find(params[:recipient]).username %></h4>

	<% else %>	
		<div class="form-group">
			<%= label_tag 'recipients', 'To:' %>
			<%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control select-js' %>
		</div>
	<% end %>

	<div class="form-group">
		<%= label_tag 'message[body]', 'Message' %>
		<%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control new-message-box', required: true %>
	</div>


	<%= submit_tag 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/conversations/show.html.erb
<div class="row">

	<div class="col-sm-3">

		<p><%= link_to 'Start conversaton', new_message_path, class: 'btn btn-lg btn-primary' %></p>

		<ul class="nav nav-tabs">
			<%= mailbox_section 'inbox', @box %>
<!--			<%= mailbox_section 'sent', @box %>	-->
			<%= mailbox_section 'trash', @box %>
		</ul>		

		<% if @box == 'trash' %>
			<p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
											data: {confirm: 'Are you sure?'} %></p>
		<% end %>
		<ul class="list-group">
			<%= render partial: 'conversations/conversation', collection: @conversations %>
		</ul>

		<%= will_paginate %>

	</div>

	<div class="col-sm-9">
		<div class="panel panel-default">
			<div class="panel-heading">

				<% @conversation.participants.each do |participant| %>
					<% unless participant == current_user %>
						<span class="message-username"><%= participant.username %></span>
					<% end %>
				<% end %>
			</div>
			<div class="panel-body">
				<div class="messages">
					<% @conversation.receipts_for(current_user).reverse.each do |receipt| %>
						<div class="media">
							<% message = receipt.message %>
							<div class="media-left">
								<div class="dream-left">
									<%= link_to message.sender do %>
										<% if message.sender.avatar_file_name.nil? %>
											<div class="dream-avatar-default">
												<p><%= message.sender.username.first.upcase %></p>
											</div>						
										<% else %>
											<%= image_tag message.sender.avatar.url(:thumb) %>
										<% end %>
									<% end %>
								</div>
							</div>

							<div class="media-body">
								<h6 class="media-heading"><%= message.sender.username %>
									says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
								<%= message.body.html_safe %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		</div>

		<%= form_tag reply_conversation_path(@conversation), method: :post do %>
			<div class="form-group">
				<%= text_area_tag 'body', nil, cols: 3, class: 'form-control message-reply-box', placeholder: 'Type something...', required: true %>
			</div>
			<%= submit_tag "Send message", class: 'btn btn-primary' %>
		<% end %>		

	</div>
</div>