config/routes.rb
Jhad::Application.routes.draw do

  

  root 'dreams#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations' }

  devise_scope :user do
    match '/sso',    to: 'discourse_sso#sso',    via: 'get'
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dreams do
    resources :comments
    member do
      put 'like', to: "dreams#upvote"
      put "dislike", to: "dreams#downvote"
    end
  end

  resources :articles do
    resources :comments
  end
  
  resources :conversations, only: [:index, :show, :destroy, :new] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]
  resources :notifications
  resources :hashtags
  resources :screennames
  resources :relationships, only: [:create, :destroy]
  

  match '/feed',    to: 'static_pages#home',    via: 'get'
  match '/blog',    to: 'articles#index',    via: 'get'
  match '/faq',    to: 'static_pages#faq',    via: 'get'
  match '/resources',    to: 'static_pages#resources',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/about2',   to: 'static_pages#about2',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/graph', to: 'static_pages#graph', via: 'get'
  match '/test', to: 'static_pages#test', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/sitemap.xml', to: 'static_pages#sitemap', format: 'xml', as: :sitemap, via: 'get'

  

  

  get 'dreams/new' => 'dreams#new', :as => :new     # For new dream modal

  get ':controller(/:action(/:id))'

end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :word_freq, Hash
  serialize :word_freq_public, Hash
  serialize :hash_freq, Hash
  serialize :hash_freq_public, Hash

  has_many :dreams, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :screennames, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower



  acts_as_voter
  acts_as_messageable

  has_attached_file :avatar, :styles => { :large => "200x200#", :medium => "70x70#", :thumb => "48x48#" }, :default_url => "/images/:style/missing.jpeg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: { without: /\s/ }
  validates :name, presence: true

  include PgSearch
  multisearchable against: [:username, :name, :email, :graph_public]  

  #before_save :check_if_new
  after_create :send_welcome_message

  alias :devise_valid_password? :valid_password?

  # Allows for old jhad passwords
  def valid_password?(password)
    begin
      super(password)
    rescue BCrypt::Errors::InvalidHash
      return false unless Digest::SHA256.hexdigest(password) == encrypted_password
      logger.info "User #{email} is using the old password hashing method, updating attribute."
      self.password = password
      true
    end
  end

  # Method for Devise to use either username or email to login.
  # This is the correct method you override with the code below:
  # def self.find_for_database_authentication(warden_conditions)
  # end
  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
  		where(conditions).where(["lower(username) = :value OR lower(email) = :value", 
  														{ :value => login.downcase }]).first 
  	else
  		where(conditions).first
  	end
  end

  # Method for finding user from OmniAuth callback or creating that user.
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      if user.provider == 'twitter'
        user.username = auth.info.nickname
        user.name = auth.info.name
      elsif user.provider == 'facebook'
        user.username = auth.info.first_name + '.' + auth.info.last_name
        user.name = auth.info.name
        user.email = auth.info.email
      elsif user.provider == 'google_oauth2'
        user.username = auth.info.first_name + '.' + auth.info.last_name
        user.name = auth.info.name
        user.email = auth.info.email      
      else  # yahoo
        user.username = auth.info.name
        user.name = auth.info.name
      end
    end
  end

  # Override Devise user class method. To handle OmniAuth callback failures, showing error
  # messages. Set the callback attributes back to user model to be validated at signup form.
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      # create new user record based on OmniAuth callback details
      new(session["devise.user_attributes"], without_protection: true) do |user|
        # Set attributes again via params hash, which is attributes send by user through form
        user.attributes = params
        # Validate user to ensure display of validation errors
        user.valid?
      end
    else
      # Fall back to normal Devise behavior--creating a new user instance
      super
    end
  end

  # for Google oath2
 # def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
 #   data = access_token.info
 #   user = User.where(:email => data["email"]).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data["name"],
    #        email: data["email"],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
#    user
#  end


  # Override method on user model so that users using OmniAuth don't require password.
  def password_required?
    # Fall back to default behavior and ensure provider is blank.
    super && provider.blank?
  end

  def email_required?
    super && provider.blank?
  end

  # Override method so that OmniAuth users (without passwords) can update their info w/o passwords.
  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  # Follows a user
  def follow(other_user)
    self.active_relationships.create(followed_id: other_user.id)
    Notification.create(user: other_user, other_user_id: self.id, subject: 'follow')
  end

  # Unfollows a user
  def unfollow(other_user)
    self.active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user
  def following?(other_user)
    self.following.include?(other_user)
  end

  # Returns a user's status feed
  def feed
    Dream.from_users_followed_by(self)
  end

  # For Mailboxer
  def mailboxer_email(object)
    if object.class==Mailboxer::Notification
      return nil
    else
      self.email
    end
  end

  #def check_if_new
  #  @is_new_record = self.new_record?
  #end

  def send_welcome_message

    User.find_by(username: 'dreamly').send_message(self, "Welcome to the Collective Unconscious. Welcome to Dreamly.<br/><br/>

We invite you to participate in our social experiment. We invite you to find yourself through others.<br/><br/>

Dreamly is a social dream journal designed to help you better understand yourself, particularly on an unconscious level. Having the functionality to post and keep track of your dreams on a private and personal level, as well as interact publically with other users through dream comparison and messaging features, Dreamly is a uniquely designed platform aiming to cut through the illusion.<br/><br/>

Social Media, up to this point, has been a testament to the exterior self. Innovations of our generation like Facebook and Twitter have allowed us to express the physical conceptions of ourselves to the online community. Whether a quick selfie or an elaborately constructed status post, . But what about the matter beneath the surface? What about the underlying layers of the psyche not receiving attention—the core emotional and psychological desires for wellbeing sewn deeply within the self?<br/><br/>

Here at Dreamly we are looking to change the model of social media. We are looking in a different direction. We are looking inward. We are seeking to lift the veil once and for all by bringing together the Collective Unconscious—the inner connection that us humans intimately share.<br/><br/>

Dreamly is in its alpha stages. We have a vision, but we are looking to better shape that vision using your input.<br/><br/>

That’s why we need your voice.<br/><br/>

We’re not asking for you to complete a hundred-question survey or to fill out a form with all of your demographical information. We want your feedback in your own words. We might throw one or two questions in to help guide us in our way, but what we really want is to hear exactly what you think of the site as is, and, any additional features that would improve your experience. Give us feedback by going to the <a href='http://community.dreamly.io/session/sso?return_path=%2F'>Dreamly Community forums</a>.<br/><br/>

We hope you enjoy your experience here at Dreamly.io. We look forward hearing from you.<br/><br/>

Pleasant Dreaming,<br/><br/>

The Dreamly Team", "Welcome message")
    self.notify('Message', 'You received a message')
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	# Gets rid of 'Unprocessable Entity' login error.
	protect_from_forgery

	def index
		@users = User.paginate(page: params[:page], per_page: 100).order('dream_count DESC')
	end

	def show
		if params[:id].nil?
			@user = current_user
		else
			@user = User.find(params[:id])
		end

		if params[:hashtag]
			@hashtag = Hashtag.find_by(name: params[:hashtag])
			if @hashtag == nil
				@dreams = @user.dreams.where(title: 'asdf7vx')
			else
				@dreams = @hashtag.dreams.where(user: @user)
			end
		else
			@dreams = @user.dreams
		end

		@filterrific = initialize_filterrific(
			@dreams,
			params[:filterrific],
			select_options: {
				with_emotion_id: Emotion.options_for_select
			},
		) or return 

		@dreams = @filterrific.find

#		@dreams = @user.dreams.regular.paginate(page: params[:page])
		
	

		if @user != current_user
			@dreams = @dreams.where(private: false)
		end

		if params[:sort] == 'trending'
			@dreams = @dreams.hot
		elsif params[:sort] == 'submitted'
			@dreams = @dreams.regular
		elsif params[:sort] == 'dreamed'
			@dreams = @dreams.chronological
		else
			@dreams = @dreams.chronological
		end


		@dreams_raw = @dreams  # try to get graph to update with filterrific
		@dreams = @dreams.paginate(page: params[:page],per_page: 15)

		


	#		@dreams = @dreams_raw.paginate(page: params[:page])
		


#		if params[:impression].present?
#			@dreams = @user.dreams.regular.impression(params[:impression]).paginate(page: params[:page])
#		elsif params[:query].present?
#			@dreams = Dream.text_search(params[:query]).paginate(page: params[:page]).where(user: @user)
	#		@dreams = Dream.text_search(params[:query]).page(params[:page])
#		end

		@hashes = Hash.new
		@screennames = Hash.new
		@emotions = Hash.new

		@dreams_raw.each do |dream|
			dream.screennames.each do |screenname|
				if @screennames[screenname.id].nil?
					@screennames[screenname.id] = 1
				else
					@screennames[screenname.id] += 1
				end
			end

			dream.emotions.each do |emotion|
				if @emotions[emotion.id].nil?
					@emotions[emotion.id] = 1
				else
					@emotions[emotion.id] += 1
				end
			end

			dream.hashtags.each do |hashtag|
				if @hashes[hashtag.id].nil?
					@hashes[hashtag.id] = 1
				else
					@hashes[hashtag.id] += 1
				end
			end
		end

		@screennames = @screennames.sort_by { |k, v| v }
		@screennames.reverse!

		@emotions = @emotions.sort_by { |k, v| v }
		@emotions.reverse!		

		@hashes = @hashes.sort_by { |k, v| v }
		@hashes.reverse!

		


	# Graph logic

		@word_count = Hash.new
		# Create hash of word frequencies in all relevant dreams
		@dreams_raw.each do |dream|
			dream.word_freq.each do |stem, info_array|
				if @word_count[info_array[0]] == nil
					@word_count[info_array[0]] = { freq: info_array[1], dream_ids: [dream.id] }
				else
					@word_count[info_array[0]][:freq] += info_array[1]
					@word_count[info_array[0]][:dream_ids].push(dream.id)
				end
			end
		end
		# Create hash with key = word_id, and v = freq, to be sortable
		@word_count_sort = Hash.new(0)
		@word_count.each do |k, v|
			@word_count_sort[k] = v[:freq]
		end
		
		@word_count_sort = @word_count_sort.sort_by { |k, v| v }
		@word_count_sort.reverse!

		if params[:graph]
			@min_words_constant = 15
			@min_assocs_constant = 2
		else
			@min_words_constant = 5
			@min_assocs_constant = 2
		end

		@nodes = Array.new

		@min_words = [@word_count.length, @min_words_constant].min
		@min_words.times do |n|
			@nodes.push(@word_count_sort[n][0])			#@word_count_sort has become an array.
		end

		@links = Array.new

		@min_words.times do |n|
			@word_object_id = @nodes[n]
			@word_object_assocs = Hash.new(0)
			@word_object_dreams = @word_count[@word_object_id][:dream_ids]

			@word_object_dreams.each do |dream_id|
				Dream.find(dream_id).word_freq.each do |stem, info_array|
					if info_array[0] != @word_object_id
						@word_object_assocs[info_array[0]] += info_array[1]
					end
				end
			end

			@word_object_assocs = Hash[@word_object_assocs.sort_by{|k, v| v}.reverse]
			@min_assocs = [@word_object_assocs.length, @min_assocs_constant].min
			@min_assocs.times do |i|
				if @nodes.include? @word_object_assocs.keys[i]		# if the association is already a node
					@links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])])	# write the link
				else @nodes.include? @word_object_assocs.keys[i]		
					@nodes.push(@word_object_assocs.keys[i])
					@links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])])
				end
			end
		end


		@node_text = "["
		@nodes.each do |word_id|

			@node_text += "{\"name\":\"#{word_id}\",\"value\":#{@word_count[word_id][:freq]}},"
		end
		@node_text = @node_text[0..-2] unless @nodes.empty?				# remove extra comma

		@node_text += "]"

		@link_text = "["
		@links.each do |link|
			@link_text += "{\"source\":#{link[0]},\"target\":#{link[1]}},"
		end

		@link_text = @link_text[0..-2] unless @links.empty?		# remove extra comma

		@link_text += "]"

		@graph_text = "{\"nodes\":#{@node_text},\"links\":#{@link_text}}"		

		# Word association logic
#		@first_word_id = @user.word_freq.keys[0]
#		@first_word = Word.find(@first_word_id)	# Find most frequent Word
#		@first_word_dreams = Array.new
#		@first_word_assocs = Hash.new(0)
		# Set array with dream_ids of @user which contain @first_word
#		@first_word.dreams.each do |dream_id|
#			if Dream.find(dream_id).user_id == @user.id
#				@first_word_dreams.push(dream_id)
#			end
#		end

#		@first_word_dreams.each do |dream_id|														# Iterate through each dream
#			Dream.find(dream_id).word_freq.each do |word_id, frequency|		# Iterate through each unique word
#				if word_id != @first_word_id
#					@first_word_assocs[word_id] += frequency										# Add word count to @first_word_assocs hash
#				end
#			end
#		end

#		@first_word_assocs = Hash[@first_word_assocs.sort_by{ |k, v| v }.reverse]

#		@first_word_first_assoc_id = @first_word_assocs.keys[0]
#		@first_word_first_assoc = Word.find(@first_word_first_assoc_id)

	end

	def graph
		@user = User.find(params[:id])
	end

	def following
		@title = "Following"
		@user = User.find(params[:id])
		@users = @user.following.paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user = User.find(params[:id])
		@users = @user.followers.paginate(page: params[:page])
		render 'show_follow'
	end


end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com) for the given user.
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "avatar")
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build(followed_id: @user.id), remote: true) do |f| %>
	<div><%= hidden_field_tag :followed_id, @user.id %></div>
	<%= f.submit "Follow", class: "btn btn-large btn-primary btn-follow" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
	<div>
		<% div_id = "follow_form_#{@user.id}" %>
		<div id="<%= div_id %>" class="follow-button">
			<% if current_user.following?(@user) %>
				<%= render 'users/unfollow' %>
			<% else %>
				<%= render 'users/follow' %>
			<% end %>
		</div>
		<div class="user-show-message">
			<% conv_check_1 = Mailboxer::Conversation.participant(@user) %>
			<% conv_check_2 = Mailboxer::Conversation.participant(current_user) %>
			<% @dialog = (conv_check_1 & conv_check_2).first %>
			<% if @dialog.nil? or !@dialog.is_participant?(current_user) %>
				<%= link_to new_message_path(recipient: @user), class: "btn btn-primary btn-message" do %>
					<%= icon('envelope') %>
				<% end %>
			<% else %>
				<%= link_to conversation_path(@dialog), class: "btn btn-primary btn-message" do %>
					<%= icon('envelope') %>
				<% end %>
			<% end %>		
		</div>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-large btn-success btn-follow" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Dreamers') %>


<h3 class="content-title">Dreamers</h3>


<div class="users" id="user-list">
	<%= render @users %>
</div>

<div id="infinite-scrolling">
	<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/users/show.html.erb
<% if params[:graph] %>
	<div id="graph-full" class="white-panel">
		<h3 class="graph-title"><%= @user.name %>'s <%= impression_status() %> dreams
			<% if params[:query] %>
			about <strong><%= params[:query] %></strong>
			<% end %>
		</h3>
		<div id="full-screen-icon" rel="tooltip" data-toggle="tooltip" data-container="body" title="Minimize">
			<%= link_to(user_path(@user.id, query: params[:query], impression: params[:impression])) do %>
				<%= icon('compress') %>
			<% end %>
		</div>		
	</div>
	<%= render 'users/graph_full' %>
<% else %>

<% provide(:title, @user.username) %>

<div class="row">
	<div class ="col-md-3">
		<div id="profile-left-sidebar">
			<div class="dashboard white-panel dashboard-avatar-container">
				<div class ="profile-upper-background">
				</div>
				
<!--					<%= gravatar_for @user %>	-->
					<% if current_user == @user %>
						<%= link_to @user do %>
							<% if @user.avatar_file_name.nil? %>
								<div class="dashboard-avatar-default">
									<p><%= @user.username.first.upcase %></p>
								</div>
							<% else %>
								<div class="dashboard-avatar">
									<%= image_tag @user.avatar.url(:medium), class: "img-center" %>
								</div>
							<% end %>
						<% end %>
					<% else %>
						<%= link_to @user do %>
							<% if @user.avatar_file_name.nil? %>
								<div class="dashboard-avatar-default">
									<p><%= @user.username.first.upcase %></p>
								</div>
							<% else %>
								<div class="dashboard-avatar">
									<%= image_tag @user.avatar.url(:medium), class: "img-center" %>
								</div>
							<% end %>
						<% end %>
					<% end %>
				
				<div class="dashboard-usernames black-links">
					<div class="dashboard-usernames-name">
						<%= link_to @user.name, @user %>
					</div>
					<div class="dashboard-usernames-handle">
						<%= link_to "@#{@user.username}", @user %>
					</div>
				</div> 
				<div class="dashboard-stats">
					<div class="dashboard-stats-left">
						<%= link_to @user do %>
							<span class="stat-header">DREAMS</span> <br />
							<span class="stat-number"><%= @user.dreams.count %></span>
						<% end %>

					</div>
					<div class="dashboard-stats-middle">
						<%= link_to following_user_path(@user) do %>
							<span class="stat-header">FOLLOWING</span> <br />
							<% following_id = "following_#{@user.id}" %>
							<span id="<%= following_id %>" class="stat-number"><%= @user.following.count %></span>
						<% end %>		
					</div>					
					<div class="dashboard-stats-right">
						<%= link_to followers_user_path(@user) do %>
							<span class="stat-header">FOLLOWERS</span> <br />
							<% followers_id = "followers_#{@user.id}" %>
							<span id="<%= followers_id %>" class="stat-number"><%= @user.followers.count %></span>
						<% end %>			
					</div>

				</div>
				<%= render 'follow_form' if user_signed_in? %>
			
			</div>
	
	<!--
			<div data-spy="affix" data-offset-top="240">
	-->
			<div>
				<% if @user.dreams.any? %>
					<div id="profile-graph" class="white-panel">
						<%= link_to(user_path(@user.id, graph: true, query: params[:query], impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Fullscreen"}) do %>
							<%= icon('arrows-alt') %>
						<% end %>
					</div>
					<div id="profile-graph2">
						<%= render(
							partial: 'users/graph',
							locals: { graph_text: @graph_text }
						) %>
					</div>

				<% end %>

				<div id="emotion-listing">
					<%= render(
						partial: 'users/emotions',
						locals: { emotions: @emotions }
					) %>
				</div>

				<div id="hash-listing">
					<%= render(
						partial: 'users/tags',
						locals: { hashes: @hashes }
					) %>
				</div>

				<% if @user == current_user %>
					<div id="name-listing">
						<%= render(
							partial: 'dreams/screennames',
							locals: { screennames: @screennames }
						) %>
					</div>
				<% end %>
	
<!--
					<% if @user == current_user %>

						<% @user.hash_freq.each do |hashtag_id, freq| %>
							<%= link_to user_path(@user.id, hashtag: Hashtag.find(hashtag_id).name), { :class => "btn user-hash-link hashtag-color" } do %>
								#<%= Hashtag.find(hashtag_id).name %>
								(<%= freq %>)
							<% end %>
						<% end %>					

					<% else %>
			
						<% @user.hash_freq_public.each do |hashtag_id, freq| %>
							<%= link_to user_path(@user.id, hashtag: Hashtag.find(hashtag_id).name), { :class => "btn user-hash-link hashtag-color" } do %>
								<%= Hashtag.find(hashtag_id).name %>
								(<%= freq %>)
							<% end %>
						<% end %>

					<% end %>	
-->
	
<!--
				<div id="links-panel" class="white-panel">
					<%= link_to "Home", root_path %>
					<%= link_to "About", about_path %>
					<%= link_to "Contact", contact_path %>
					<%= image_tag("footer_stripe.jpg", width: '243', height: '10', class: 'rainbow-bar') %>
				</div>
-->

					<div class="share-box">
					</div>	

			</div>
		</div>
	</div>
	<div class="col-md-9">
		<% if params[:hashtag] %>
			<h3 class="content-title">#<%= params[:hashtag] %></h3>
		<% end %>

		<div class="dream-tabs">
			<% if params[:sort] == "trending" %>
				<ul class="nav nav-tabs">
			    <li role="presentation" class="active"><%= link_to "Trending", user_path(@user.id, sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation"><%= link_to "New", user_path(@user.id, sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation"><%= link_to "Dreamed", user_path(@user.id, sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				</ul>
			<% elsif params[:sort] == "submitted" %>	
				<ul class="nav nav-tabs">
			    <li role="presentation"><%= link_to "Trending", user_path(@user.id, sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation" class="active"><%= link_to "New", user_path(@user.id, sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation"><%= link_to "Dreamed", user_path(@user.id, sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				</ul>
			<% elsif params[:sort] == "dreamed" %>	
				<ul class="nav nav-tabs">
			    <li role="presentation"><%= link_to "Trending", user_path(@user.id, sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation"><%= link_to "New", user_path(@user.id, sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation" class="active"><%= link_to "Dreamed", user_path(@user.id, sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				</ul>		
			<% else %>	
				<ul class="nav nav-tabs">
			    <li role="presentation"><%= link_to "Trending", user_path(@user.id, sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation"><%= link_to "New", user_path(@user.id, sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
			    <li role="presentation" class="active"><%= link_to "Dreamed", user_path(@user.id, sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				</ul>										
			<% end %>
		</div>

			<div id="filter-block">
				<%= form_for_filterrific @filterrific do |f| %>
				
						
						<%= f.text_field(
							:search,
							placeholder: "Search...",
							class: 'filterrific-periodically-observed'
						) %>

					
						<%= f.select(
							:with_emotion_id,
							@filterrific.select_options[:with_emotion_id],
							{ include_blank: 'Emotion' },
							class: "select-js"
						) %>

				
						<%= f.select(
							:impression,
							[['Normal', 1], ['Substantial', 2], ['Epic', 3]],
							{ include_blank: 'Impact' },
							class: "select-js",
						) %>
				
						<%= link_to(reset_filterrific_url) do %>
							<%= icon('times') %>
						<% end %>
						<%= render(
							partial: 'dreams/list_count',
							locals: { dreams: @dreams }
						) %>	

						
					<div>


						
						<%= render_filterrific_spinner %>
					</div>
					<%# add an automated spinner to your form when the list is refreshed %>
					
				<% end %>
			</div>
			


				<%= render(
					partial: 'users/list',
					locals: { dreams: @dreams }
				) %>



			<% if @dreams.total_pages > 1 %>
				<%= button_tag(:id => "load-more", :class => "btn btn-primary") do %>
					<%= icon('plus') %>
					<span id="load-more-text">load more</span>
				<% end %>
			<% end %>	



				<% if @user.dreams.any? %>
				
				<% elsif current_user == @user %>
					<%= render 'dreams/firstnew' %>
				<% end %>
		
	</div>
</div>

<% end %>