config/routes.rb
Jhad::Application.routes.draw do

  

  root 'dreams#index'

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" },
                     controllers: { omniauth_callbacks: "omniauth_callbacks", sessions: 'sessions', registrations: 'registrations' }

  devise_scope :user do
    match '/sso',    to: 'discourse_sso#sso',    via: 'get'
  end

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dreams do
    resources :comments
    member do
      put 'like', to: "dreams#upvote"
      put "dislike", to: "dreams#downvote"
    end
  end

  resources :articles do
    resources :comments
  end
  
  resources :conversations, only: [:index, :show, :destroy, :new] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]
  resources :notifications
  resources :hashtags
  resources :screennames
  resources :relationships, only: [:create, :destroy]
  

  match '/feed',    to: 'static_pages#home',    via: 'get'
  match '/blog',    to: 'articles#index',    via: 'get'
  match '/faq',    to: 'static_pages#faq',    via: 'get'
  match '/resources',    to: 'static_pages#resources',    via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/about2',   to: 'static_pages#about2',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'
  match '/graph', to: 'static_pages#graph', via: 'get'
  match '/test', to: 'static_pages#test', via: 'get'
  match '/search', to: 'static_pages#search', via: 'get'
  match '/sitemap.xml', to: 'static_pages#sitemap', format: 'xml', as: :sitemap, via: 'get'

  

  

  get 'dreams/new' => 'dreams#new', :as => :new     # For new dream modal

  get ':controller(/:action(/:id))'

end

app/models/screenname.rb
class Screenname < ActiveRecord::Base

	belongs_to :user
	has_many :dreamscreennames
	has_many :dreams, through: :dreamscreennames

end

app/controllers/screennames_controller.rb
class ScreennamesController < ApplicationController
	before_filter :correct_user

	def show
		@screenname = Screenname.find(params[:id])
		@dreams = @screenname.dreams

		@filterrific = initialize_filterrific(
			@dreams,
			params[:filterrific],
			select_options: {
				with_emotion_id: Emotion.options_for_select
			},
			default_filter_params: { search: params[:search] },
		) or return

		@dreams = @filterrific.find

		if params[:sort] == 'trending'
			@dreams = @dreams.hot
		elsif params[:sort] == 'submitted'
			@dreams = @dreams.regular
		elsif params[:sort] == 'dreamed'
			@dreams = @dreams.chronological
		else
			@dreams = @dreams.chronological
		end

		@dreams2 = @dreams.paginate(page: params[:page],per_page: 15)
		
		@page_number = params[:page].to_i
		if params[:page].nil?
			@dreams = @dreams.paginate(page: params[:page],per_page: 15)
		elsif params[:page] == 1
			@dreams = @dreams.paginate(page: params[:page],per_page: 15)
		else
			@cumul = @dreams.paginate(page: 1,per_page: 15)
			(@page_number - 1).times do |i|
				@dreams.paginate(page: i + 2,per_page: 15).each do |dream|
					@cumul = @cumul << dream
				end
			end
			@dreams = @cumul
		end

	

		@hashes = Hash.new
		@screennames = Hash.new
		@emotions = Hash.new

		@dreams.each do |dream|
			dream.screennames.each do |screenname|
				if @screennames[screenname.id].nil?
					@screennames[screenname.id] = 1
				else
					@screennames[screenname.id] += 1
				end
			end

			dream.emotions.each do |emotion|
				if @emotions[emotion.id].nil?
					@emotions[emotion.id] = 1
				else
					@emotions[emotion.id] += 1
				end
			end					

			dream.hashtags.each do |hashtag|
				if @hashes[hashtag.id].nil?
					@hashes[hashtag.id] = 1
				else
					@hashes[hashtag.id] += 1
				end
			end
		end

		@screennames = @screennames.sort_by { |k, v| v }
		@screennames.reverse!

		@emotions = @emotions.sort_by { |k, v| v }
		@emotions.reverse!		

		@hashes = @hashes.sort_by { |k, v| v }
		@hashes.reverse!

	# Graph logic

		@word_count = Hash.new
		# Create hash of word frequencies in all relevant dreams
		@dreams.each do |dream|
			if (dream.private == false) || dream.user = current_user
				dream.word_freq.each do |stem, info_array|
					if @word_count[info_array[0]] == nil
						@word_count[info_array[0]] = { freq: info_array[1], dream_ids: [dream.id] }
					else
						@word_count[info_array[0]][:freq] += info_array[1]
						@word_count[info_array[0]][:dream_ids].push(dream.id)
					end
				end
			end
		end
		# Create hash with key = word_id, and v = freq, to be sortable
		@word_count_sort = Hash.new(0)
		@word_count.each do |k, v|
			@word_count_sort[k] = v[:freq]
		end
		
		@word_count_sort = @word_count_sort.sort_by { |k, v| v }
		@word_count_sort.reverse!

		if params[:graph]
			@min_words_constant = 15
			@min_assocs_constant = 2
		else
			@min_words_constant = 5
			@min_assocs_constant = 2
		end		

		@nodes = Array.new
		@min_words = [@word_count.length, @min_words_constant].min
		@min_words.times do |n|
			@nodes.push(@word_count_sort[n][0])			#@word_count_sort has become an array.
		end

		@links = Array.new

		@min_words.times do |n|
			@word_object_id = @nodes[n]
			@word_object_assocs = Hash.new(0)
			@word_object_dreams = @word_count[@word_object_id][:dream_ids]

			@word_object_dreams.each do |dream_id|
				Dream.find(dream_id).word_freq.each do |stem, info_array|
					if info_array[0] != @word_object_id
						@word_object_assocs[info_array[0]] += info_array[1]
					end
				end
			end

			@word_object_assocs = Hash[@word_object_assocs.sort_by{|k, v| v}.reverse]
			@min_assocs = [@word_object_assocs.length, @min_assocs_constant].min
			@min_assocs.times do |i|
				if @nodes.include? @word_object_assocs.keys[i]		# if the association is already a node
					@links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])])	# write the link
				else @nodes.include? @word_object_assocs.keys[i]		
					@nodes.push(@word_object_assocs.keys[i])
					@links.push([@nodes.index(@word_object_id), @nodes.index(@word_object_assocs.keys[i])])
				end
			end
		end


		@node_text = "["
		@nodes.each do |word_id|

			@node_text += "{\"name\":\"#{word_id}\",\"value\":#{@word_count[word_id][:freq]}},"
		end
		@node_text = @node_text[0..-2] unless @nodes.empty?				# remove extra comma

		@node_text += "]"

		@link_text = "["
		@links.each do |link|
			@link_text += "{\"source\":#{link[0]},\"target\":#{link[1]}},"
		end

		@link_text = @link_text[0..-2] unless @links.empty?		# remove extra comma

		@link_text += "]"

		@graph_text = "{\"nodes\":#{@node_text},\"links\":#{@link_text}}"	
		
	end

	private

		def correct_user
			@dream = current_user.dreams.find_by(id: params[:id])
			redirect_to root_url if @dream.nil?
		end




end

app/views/screennames/show.html.erb
<% provide(:title, @screenname.name) %>


<% if params[:graph] %>
	<div id="graph-full" class="white-panel">
		<h3 class="graph-title"><%= impression_status().titleize %>
			<% unless params[:impression] %>
				All
			<% end %>
			dreams
			<% if params[:query] %>
			about <strong><%= params[:query] %></strong>
			<% end %>
		</h3>
		<%= link_to dreams_path(query: params[:query], impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Minimize"} do %>
			<%= icon('compress') %>
		<% end %>	
	</div>
	<%= render 'dreams/graph_full' %>

<% else %>

<div class="row">
	<div class ="col-md-3">
		<div id="profile-left-sidebar">
			<div>
				<% if @dreams.any? %>
					<div id="profile-graph" class="white-panel">
						<%= link_to screenname_path(@screenname.id, graph: true, impression: params[:impression]), { id: 'full-screen-icon', "data-toggle" => "tooltip", "data-container" => "body", title: "Fullscreen"} do %>
							<%= icon('arrows-alt') %>
						<% end %>
					</div>
					<div id="profile-graph2">
						<%= render 'dreams/graph' %>
					</div>
				<% end %>

				<div id="emotion-listing">
					<%= render(
						partial: 'dreams/emotions',
						locals: { emotions: @emotions }
					) %>
				</div>					

				<div id="hash-listing">
					<%= render(
						partial: 'dreams/tags',
						locals: { hashes: @hashes }
					) %>
				</div>
				<div id="name-listing">
					<%= render(
						partial: 'dreams/screennames',
						locals: { screennames: @screennames }
					) %>
				</div>

				<div id="links-panel" class="white-panel">
					<%= link_to "Home", root_path %>
					<%= link_to "About", about_path %>
					<%= link_to "Contact", contact_path %>
					<%= image_tag("footer_stripe.jpg", width: '243', height: '10', class: 'rainbow-bar') %>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-9">
		<div>
			<h3 class="content-title">@<%= @screenname.name %></h3>

			<div class="dream-tabs">
				<% if params[:sort] == "trending" %>
					<ul class="nav nav-tabs">
				    <li role="presentation" class="active"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>
				<% elsif params[:sort] == "submitted" %>	
					<ul class="nav nav-tabs">
				    <li role="presentation"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation" class="active"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>
				<% elsif params[:sort] == "dreamed" %>	
					<ul class="nav nav-tabs">
				    <li role="presentation"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation" class="active"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>		
				<% else %>	
					<ul class="nav nav-tabs">
				    <li role="presentation" class="active"><%= link_to "Trending", dreams_path(sort: 'trending'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "New", dreams_path(sort: 'submitted'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
				    <li role="presentation"><%= link_to "Dreamed", dreams_path(sort: 'dreamed'), html_options = { :role => "menuitem", :tabindex => "-1" } %></li>
					</ul>										
				<% end %>
			</div>			

			<div id ="filter-block">
				<%= form_for_filterrific @filterrific do |f| %>
							
						<%= f.text_field(
							:search,
							placeholder: 'Search...',
							class: 'filterrific-periodically-observed'
						) %>

					
						<%= f.select(
							:with_emotion_id,
							@filterrific.select_options[:with_emotion_id],
							{ include_blank: 'Emotion' },
							class: "select-js"
						) %>
		

						<%= f.select(
							:impression,
							[['Normal', 1], ['Substantial', 2], ['Epic', 3]],
							{ include_blank: 'Impact' },
							class: "select-js"
						) %>
		
						<%= link_to(reset_filterrific_url) do %>
							<%= icon('times') %>
						<% end %>	

						<%= render(
							partial: 'dreams/list_count',
							locals: { dreams: @dreams }
						) %>						

						<div>
							<%# add an automated spinner to your form when the list is refreshed %>
							<%= render_filterrific_spinner %>
						</div>					

				<% end %>
			</div>

			<%= render(
				partial: 'dreams/list',
				locals: { dreams: @dreams, dreams2: @dreams2 }
			) %>

			<%= button_tag(:id => "load-more2", :class => "btn btn-primary") do %>
				<%= icon('plus') %>
				<span id="load-more-text">load more</span>
			<% end %>	



		</div>




	</div>
</div>

<% end %>